name: CallFix Build and Push

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write
  packages: write

concurrency:
  group: callfix-build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and sync
        run: |
          git remote add upstream https://github.com/open-webui/open-webui.git || git remote set-url upstream https://github.com/open-webui/open-webui.git
          git fetch upstream
          git fetch origin
          git checkout -B callfix-build upstream/main
          # Bring in patch artifacts from our feature branch so we can apply them on top of upstream/main
          git checkout origin/feature/call-chunked-mode -- patches scripts

      - name: Reapply CallOverlay patch
        run: |
          chmod +x scripts/reapply-patch.sh || true
          ./scripts/reapply-patch.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/in-neil/open-webui
          tags: |
            type=raw,value=callfix-latest
            type=sha,format=short,prefix=callfix-
          labels: |
            org.opencontainers.image.title=Open WebUI CallFix
            org.opencontainers.image.description=Fork build with chunked continuous recording (Option B) for iOS; frontend-only patch.
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=AGPL-3.0
            io.github.in-neil.callfix=true
            io.github.in-neil.workflow=callfix-build

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Output image tags
        run: |
          echo "Published tags:\n${{ steps.meta.outputs.tags }}"
